### ISSUE TITLE
OkCoin.cn returning several wallets for same currency.

### ISSUE THREAD

**Issue by redred77** [timmolter/XChange#1039]
I opened Loan/Lend wallet at okcoin.cn (https://www.okcoin.cn/lend/lends.do)

I think this made some difference on getting wallet list.
I currently get 6 wallets.

![xchange-okcoin](https://cloud.githubusercontent.com/assets/680980/9150568/dbda6b6c-3e1a-11e5-8921-b93d1bb84036.png)

First wallet is CNY, and it has "available" string in description.
I get some more wallets with same CNY and "loan" string in description at index 5.

Current API is just returning one wallet by currency string and I can't get normal CNY wallet that has "available" description.

I can call getWallets() and retrieve it manually but why I'm posting issue is that I found description field is deprected.
description field is important to distinguish wallets in okcoin.cn

I'm not familiar with XChange yet and I'm not sure what is better solution. Just want to say description field must not be deprecated in this situation.

**Comment by jheusser** [comment]
The Okcoin wallet implementation reflects the wallets available in the UI. One for each (available, loan, frozen). I don't know the latest state of the future of the `Wallet` class, but some fields have indeed been deprecated. Whatever implementation we settle on it has to be able to distinguish different types of balances for each currency.

**Comment by doublesharp** [comment]
I am having this same issue with ItBit, although in this case I had to expose the wallet ID to figure out what is going on. There are two wallets associated with my API key, and they are both returned by a call to `getWallets()`, as seen here ("id=" in Wallet.toString() added by me):

```
[
Wallet [currency=USD, balance=0E-8, available=0E-8, frozen=0E-8, description=, id=xxxxxxxx-c077-4f7b-a084-6d06bb2b7ee3], 
Wallet [currency=XBT, balance=0.17790000, available=0.17790000, frozen=0E-8, description=, id=xxxxxxxx-c077-4f7b-a084-6d06bb2b7ee3], 
Wallet [currency=EUR, balance=0E-8, available=0E-8, frozen=0E-8, description=, id=xxxxxxxx-c077-4f7b-a084-6d06bb2b7ee3], 
Wallet [currency=SGD, balance=0E-8, available=0E-8, frozen=0E-8, description=, id=xxxxxxxx-c077-4f7b-a084-6d06bb2b7ee3], 
Wallet [currency=USD, balance=0E-8, available=0E-8, frozen=0E-8, description=, id=xxxxxxxx-71b4-467f-92da-ff093df132e0], 
Wallet [currency=XBT, balance=0E-8, available=0E-8, frozen=0E-8, description=, id=xxxxxxxx-71b4-467f-92da-ff093df132e0], 
Wallet [currency=EUR, balance=0E-8, available=0E-8, frozen=0E-8, description=, id=xxxxxxxx-71b4-467f-92da-ff093df132e0], 
Wallet [currency=SGD, balance=0E-8, available=0E-8, frozen=0E-8, description=, id=xxxxxxxx-71b4-467f-92da-ff093df132e0]
]
```

Noticed that the `Wallet` *xxxxxxxx-c077-4f7b-a084-6d06bb2b7ee3* has a balance of XBT, however the `Wallet` *xxxxxxxx-71b4-467f-92da-ff093df132e0* does not, but comes last in the list. When you get call `AccountInfo.getWallet(Currencies.XBT)` you only get the last `Wallet`, even if you have specified a `Wallet` ID in the `ExchangeSpecification`, as seen here:

```
Wallet [currency=XBT, balance=0E-8, available=0E-8, frozen=0E-8, description=, id=xxxxxxxx-71b4-467f-92da-ff093df132e0]
```

It seems as though `Map<String, Wallet> AccountInfo.walletsMap` should take this into consideration and actually be a `Map<String, Map<String, Wallet>` with the first key being the `Wallet` ID, if available (constant "empty" value if not provided by the `Exchange`) and the second key being the currency.

The short term work around I made was to pass the `Exchange` into the Adapter and just skip over any Wallet IDs that don't match the one provided in the `ExchangeSpecification`.

**Comment by doublesharp** [comment]
@timmolter I have patched the issue of multiple Wallet types in OK Coin and IDs in ItBit, but wanted to check with you about the planned implementation before creating a pull request. In both cases I am passing in the `Exchange` so that the `ExchangeSpecification` can be accessed. A parameter in the specification is then used to determine which `Wallet` should be returned based either on the type or ID. 

If you can check out my changes and let me know if they fit in with your plans and if so I will create a pull request for them.

* OkCoin: https://github.com/doublesharp/XChange/commit/e7defd3e09bd812f278cea7c51a630da4fac9d51
* ItBit: https://github.com/doublesharp/XChange/commit/27a2828de3b77faf705c449a87b4db3756873e23

I'm also curious about the description being deprecated - what is the best way to determine Wallet specific information through the interface?

Thanks!

**Comment by jheusser** [comment]
@doublesharp @timmolter Will look at this today.

**Comment by timmolter** [comment]
@jheusser thanks!

**Comment by doublesharp** [comment]
@jheusser, thanks for checking it out. I'm noticing a similar issue on Bitfinex. If you look at their API documentation /balances documentation on this page https://www.bitfinex.com/pages/api you will see that it returns 3 different "types" of balances. The valid values are "trading", "deposit", and "exchange", however in the Bitfinex implementation it is hard coded to only return a value for "exchange": https://github.com/timmolter/XChange/blob/develop/xchange-bitfinex/src/main/java/com/xeiam/xchange/bitfinex/v1/BitfinexAdapters.java#L226.

As I mentioned earlier I might be misunderstanding the intention, but I'm confused regarding how Wallets/balances are being handled in XChange. 

Thanks again!

**Comment by jheusser** [comment]
@doublesharp Thanks for the PR. If I understand it correctly your code addresses that `AccountInfo.getWallet` returns a specific wallet by currency. `AccountInfo` and `Wallet` are a bit in a messy sad state at the moment and need refactoring. This is mainly due to the fact that exchanges added more features to their wallets and account APIs over time -- you are right `getWallet` with currency as parameter does not return a sensible result at the moment. However, the fix above is making things worse unfortunately.

It is intentional and consistently implemented across all xchange implementations (on exchanges where you can borrow currency) that all 3 balances per currency (available, borrow, frozen) are available in a single wallet. That's the only way how you can calculate your current exposure if you have borrowed amounts. Whatever refactoring we do to make AccountInfo and Wallet more sensible, we will have to keep this logic intact.

**Comment by doublesharp** [comment]
@jheusser Maybe I am misunderstanding. The issues I have had with ItBit, OkCoin, and Bitfinex are that the APIs are returning multiple balances in multiple currencies meaning that some of the currencies are repeated, however getWallet(Currency) is only showing one type in the case of ItBit and OkCoin, and Bitfinex is hardcoded to just the "exchange" type. This is largely due to the wallets Map being keyed on currency - if a currency is returned from the API more than once only one will make it through.

**ItBit**: If you look at my comment above, calling getWallets() shows multiple wallets with the same currency, the difference is that the `id` for the wallet is different. This isn't normally visible on the wallet, but I updated the adapter to use getId() for the description, even though it is deprecated. In this case the first wallet had a balance, but the second wallet did not. When I call getWallet(BTC) it was showing $0, because the balance exists on the first wallet. If you look at the code here, noticed that the getCurrency() will overwrite previous entries in the wallets HashMap if they are repeated in the response from the Exchange: https://github.com/doublesharp/XChange/blob/27a2828de3b77faf705c449a87b4db3756873e23/xchange-itbit/src/main/java/com/xeiam/xchange/itbit/v1/ItBitAdapters.java#L130. My change lets just lets you specify the walletId that you want to get the balance for as part of the ExchangeSpecification, though I'm not sure this is the best way to do it. As is the getWallet(Currency) call is *not* returning a valid account balance.

**OkCoin**: Also returns multiple wallets of different types, each containing duplicate currencies. If you don't specify the the type somehow, the same issue as above occurs where the last type overwrites the wallets Map. Since it is the loan type, only those values are returned in later getWallet(Currency) calls. You can see where it is overwritten in the map here when the List is passed into the AccountInfo constructor: https://github.com/timmolter/XChange/blob/develop/xchange-core/src/main/java/com/xeiam/xchange/dto/account/AccountInfo.java#L83

**Bitfinex**: Hardcoded to use "exchange" type, even though "trading" and "deposit" are also valid. This code effectively does what mine does, however it is hardcoded to a single value instead of letting you pass it in through the ExchangeSpecification: https://github.com/timmolter/XChange/blob/develop/xchange-bitfinex/src/main/java/com/xeiam/xchange/bitfinex/v1/BitfinexAdapters.java#L226

If you think that the changes make things worse can you explain how I can get the balance in the 3 cases above?

Thanks again!

**Comment by doublesharp** [comment]
If the implementation looked more like this I think it would align better with the responses from the exchange APIs and will maybe explain the issue a bit more clearly:

```
AccountInfo.getWallet(String idOrType).getWalletBalance(Currency currency)
```

A `Wallet` would then contain a `Map<Currency, WalletBalance>`, and `WalletBalance` would look like the current `Wallet` with values for the `available`, `borrow`, `frozen` amounts.
