### ISSUE TITLE
Question to Balance / Available / Frozen

### ISSUE THREAD

**Issue by GENiALi** [timmolter/XChange#1059]
I write a program to generate statistics for me about a bot I use. 
I check the Exchanges BTer, Poloniex, Cryptsy, Bleutrade and Bittrex.
Now, the first three exchange that I verified have not the correct values in this fields.
Question:
frozen == value that used in trades. Not available for work.
available == value available for work.
balance = frozen + avaliable.
Correct?
Bleutrade/Cryptsy/Poloniex have only available value in balance and available fields.

Sample Pononiex:
Web:
[WDC] Worldcoin 566.62130431 
On orders: 375.56498163 
BTC value: 0.02205658

XChange:
Wallet [currency=WDC, balance=566.62130431, available=566.62130431, frozen=0, description=]

Is this correct? I think no.

**Comment by timmolter** [comment]
I wouldn't be surprised if those were not 100% correct because the people who implemented them may not have place high importance on getting it right. The best way to get it right would be to fix it how you judge correct and submit a PR. @jheusser do we have definitions of those variables somewhere? Is @GENiALi 's definition correct?
