### ISSUE TITLE
Question: How to significantly expand list of supported currencies?

### ISSUE THREAD

**Issue by 21xhipster** [timmolter/XChange#1060]
Do I understand correctly that now XChange support currencies listed [here](https://github.com/timmolter/XChange/blob/develop/xchange-core/src/main/java/com/xeiam/xchange/currency/Currencies.java)?
Though currently supported by XChange exchanges have much more trading pairs.
I need to get prices for all pairs from supported exchanges for my app.
Does that possible with XChange?
How much efforts could be needed to add such support?

**Comment by timmolter** [comment]
Those currencies are just common ones, but not necessarily all the supported ones. As you know, each exchange supports a different set of currency pairs. Some provide API access to  their list, others don't. We have a mechanism in `XChange` ties to the meta data (take a look). For most exchanges that have a currency list, `XChnage` polls them and builds a list. Otherwise, there is a `.json` file in each module where the currency pairs are defined. If it's out of date, you can supply a path for an override `.json` file.

I hope that helps. I should add that to the Wiki I suppose.

**Comment by 21xhipster** [comment]
Thanks. I see there is a way to manage it. Good news. One more off topic question: Could I run XChange as a REST service for this purpose? Also didn't find any info. Regards!

**Comment by timmolter** [comment]
> Could I run XChange as a REST or Websocket service for this purpose?

No, but you could build one with XChange being the code that fetches data from multiple exchanges. You'd then wrap that with your REST service however you'd like.

**Comment by 21xhipster** [comment]
How do you think do this project need REST functionality built in?
I'd like to post bounty on it, but I need rough estimation. Otherwise we will develop this project as a fork that is to be honest not our priority at the moment.

**Comment by timmolter** [comment]
I think a REST interface is beyond the scope of this project for sure. It sounds like the best approach would be a separate project that depends on XChange.

**Comment by 21xhipster** [comment]
Thanks @timmolter!
