### ISSUE TITLE
300 mBTC Bounty - Clean up `AccountInfo`

### ISSUE THREAD

**Issue by timmolter** [timmolter/XChange#1065]
figure out best Wallets solution. See:

* <https://github.com/timmolter/XChange/issues/1039>
* <https://github.com/timmolter/XChange/issues/1059>

Propose a good solution, address TODOs, remove deprecated code, refactor all implementations and example code as needed.

**Comment by rafalkrupinski** [comment]
There is also @jheusser's input on user wallets in #919.

**Comment by mmazi** [comment]
Another AccountInfo issue is #1072 .

**Comment by baffo32** [comment]
Solution ideas:
- AccountInfo gains member `String walletId` .
- Account and Trade services may optionally implement an interface providing `setWalletId(String walletId)`.  Account service may also implement `getAllWalletIds()` and `transferTo(String walletId, CurrencyPair currencyPair, BigDecimal amount)`.  Their other methods act on the last set wallet id.  Not many exchanges use these multiple wallets.
- OkCoin's issue is only because it has not migrated to the solution agreed upon in #919 .  This is just updating the code.  `balance = available + frozen - borrowed + loaned` and/or `available = balance - loaned + borrowed - frozen` should be documented in AccountInfo.  The equation should be kept correct whether or not `borrowed` and `loaned` are actually recorded with separate members.
- Bitfinex has an issue where each wallet has differing functionality (one can trade, one can loan, one can borrow).  I think here that each wallet could be implemented as a separate Exchange, resulting in 3 Bitfinex exchanges sharing some code underneath.

**Comment by timmolter** [comment]
@baffo32 Please provide a BTC address to collect the bounty.

**Comment by baffo32** [comment]
1NiQsdUJdXh3z11DLaX3iT3QqoSYVGk2Gq

**Comment by timmolter** [comment]
@baffo32 Is this still the address you want paid to?

**Comment by xloem** [comment]
@timmolter thanks that should still work fine

**Comment by timmolter** [comment]
@xloem are you @baffo32 ?

**Comment by baffo32** [comment]
sorry!  yes that was me, good address still

**Comment by timmolter** [comment]
Paid. Thanks!!!

**Comment by currentsea** [comment]
just for your information -- it still says "open" on this page -- http://knowm.org/open-source/ :)

**Comment by timmolter** [comment]
@currentsea Thank! Fixed.
