### ISSUE TITLE
Coinbase v2 - help with authentication

### ISSUE THREAD

**Issue by Muffon** [timmolter/XChange#1132]
Hi, I have finally got some time to implement new v2 api but I have stucked right on the begining.

I would appreciate any help. I am overriding digestParams method in CoinbaseDigest.java and using API documentation from here https://developers.coinbase.com/api/v2?shell#authentication

I have chosen the users method to test it. I am still getting 401 error. I think, my generated hash is wrong.

CoinbaseAuthenticated.java
```java
 @GET
  @Path("users/{id}")
  CoinbaseUser getUser(@HeaderParam("CB-ACCESS-KEY") String apiKey, @HeaderParam("CB-ACCESS-SIGN") ParamsDigest signer,
      @HeaderParam("CB-ACCESS-TIMESTAMP") SynchronizedValueFactory<Long> nonce, @HeaderParam("id") String id) throws IOException, CoinbaseException;

```

```java 


CoinbaseDigest.java
 @Override
  public String digestParams(RestInvocation restInvocation) {
    
    String message = restInvocation.getParamValue(HeaderParam.class, "CB-ACCESS-TIMESTAMP").toString() + restInvocation.getHttpMethod() + "/"
        + restInvocation.getPath() + (restInvocation.getRequestBody() != null ? restInvocation.getRequestBody() : "");

    Mac mac256 = getMac();
      
    mac256.update(message.getBytes());
      
    String signature = Arrays.toString(mac256.doFinal());
    
    return signature ;
  }
```

**Comment by timmolter** [comment]
What's the full response? See how to see that in step 3 here: <https://github.com/timmolter/XChange/wiki/New-Implementation-Best-Practices>.

**Comment by Muffon** [comment]
Well, I have added logback.xml to src/main/resources folder in the project from witch I run the test and to the same path in the Coinbase project as well but it doesn't log anything. I have uncommented the trace line. Where should I put it?

**Comment by Muffon** [comment]
I have added a logback dependency :-)
```{"errors":[{"id":"authentication_error","message":"request timestamp expired"}],"warnings":[{"id":"missing_version","message":"Please supply API version (YYYY-MM-DD) as CB-VERSION header","url":"https://developers.coinbase.com/api#versioning"}]} ```

**Comment by Muffon** [comment]
I was missing a CB-VERSION header parameter and nonce factory is required to be in seconds instead of miliseconds. I have fixed that. Now I am getting : 401, invalid signiture

CoinbaseDigest.java

```java

public class CoinbaseDigest extends BaseParamsDigest {

  private CoinbaseDigest(String secretKey) {

    super(secretKey, HMAC_SHA_256);
  }

  public static CoinbaseDigest createInstance(String secretKey) { 
      return secretKey == null ? null : new CoinbaseDigest(secretKey); 
  }

  @Override
  public String digestParams(RestInvocation restInvocation) {
    
    String message = restInvocation.getParamValue(HeaderParam.class, "CB-ACCESS-TIMESTAMP").toString() + restInvocation.getHttpMethod() + "/"
        + restInvocation.getPath() + (restInvocation.getRequestBody() != null ? restInvocation.getRequestBody() : "");
    
    Mac mac256 = getMac();
     try {
      mac256.update(message.getBytes("UTF-8"));
    } catch (Exception e) {
      throw new ExchangeException("Digest encoding exception", e);
    }

    return Base64.encodeBytes(mac256.doFinal());
  }
}
```

**Comment by Muffon** [comment]
Hi, I have solved it. 

```java

  @Override
  public String digestParams(RestInvocation restInvocation) {
    String timeStamp = restInvocation.getParamValue(HeaderParam.class, "CB-ACCESS-TIMESTAMP").toString();
    String method = restInvocation.getHttpMethod();
    String path =  restInvocation.getPath();
    String requestBody = restInvocation.getRequestBody() != null ? restInvocation.getRequestBody() : "";
    
    String message =  timeStamp + method + "/" + path + requestBody;
    
    Mac mac256 = getMac();     
   
    BigInteger hash = new BigInteger(1, mac256.doFinal(message.getBytes()));
		String enc = hash.toString(16);
		if ((enc.length() % 2) != 0) {
			enc = "0" + enc;
		}
                String result =enc;
    
    return result;
  }  
```

Thanks!

**Comment by privato2009** [comment]
Goodmorning everyone,
I have an authentication problem with my account, through the Coinbase.com API.

I tell you what's happening to me:

- I opened a private account on Coinbase.com,
- I created my API Keys,
- I have enabled all the permissions to the keys, this means that I can perform all the operations possible with those APIs.
- I read the developer's guide and I tried to write a small script to test the authentication, but nothing completely useless ..., I return this error:

[code]
string (37) "{" success ": false," error ":" Not Found "}"
[/code]

Since the examples are in other languages ​​but I use PHP, I think I have made a mistake during the conversion of the script.

This is the link of the official guide:

https://developers.coinbase.com/docs/wallet/api-key-authentication

This is my script:

[code]
<?
$API_KEY = '<---MY API KEY--->';
$API_SECRET = '<---MY API KEY SECRET--->';

$body = '';
$timestamp = time();
$message = $timestamp . 'GET' . 'https://www.mysite.it' . $body;
$signature = hash_hmac('SHA256', $message, $API_SECRET);

$headers = array(
					'CB-ACCESS-SIGN: '.$signature,
					'CB-ACCESS-TIMESTAMP: '.$timestamp,
					'CB-ACCESS-KEY: '.$API_KEY
				); 

$api_url = 'https://api.coinbase.com/v2/user';

$ch = curl_init(); 
curl_setopt($ch, CURLOPT_URL, $api_url);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_POST, 1);
	
$data = curl_exec($ch); 


if(curl_errno($ch))
{ 
    echo "Errore: " . curl_error($ch); 
}
else
{ 
    var_dump($data); 
    curl_close($ch); 
} 
?>
[/code]

Do you give me your opinion?
I've been stuck here for 5 days and I can not understand what I'm missing.
The assistance of Coinbase does not answer me and I have a project to deliver blocked.

Thank you very much for any useful advice.

**Comment by privato2009** [comment]
Goodmorning everyone,
I have an authentication problem with my account, through the Coinbase.com API.

I tell you what's happening to me:

- I opened a private account on Coinbase.com,
- I created my API Keys,
- I have enabled all the permissions to the keys, this means that I can perform all the operations possible with those APIs.
- I read the developer's guide and I tried to write a small script to test the authentication, but nothing completely useless ..., I return this error:

`
string (37) "{" success ": false," error ":" Not Found "}"
`

Since the examples are in other languages ​​but I use PHP, I think I have made a mistake during the conversion of the script.

This is the link of the official guide:

https://developers.coinbase.com/docs/wallet/api-key-authentication

This is my script:

```
<?
$API_KEY = '<---MY API KEY--->';
$API_SECRET = '<---MY API KEY SECRET--->';

$body = '';
$timestamp = time();
$message = $timestamp . 'GET' . 'https://www.mysite.it' . $body;
$signature = hash_hmac('SHA256', $message, $API_SECRET);

$headers = array(
					'CB-ACCESS-SIGN: '.$signature,
					'CB-ACCESS-TIMESTAMP: '.$timestamp,
					'CB-ACCESS-KEY: '.$API_KEY
				); 

$api_url = 'https://api.coinbase.com/v2/user';

$ch = curl_init(); 
curl_setopt($ch, CURLOPT_URL, $api_url);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_POST, 1);
	
$data = curl_exec($ch); 


if(curl_errno($ch))
{ 
    echo "Errore: " . curl_error($ch); 
}
else
{ 
    var_dump($data); 
    curl_close($ch); 
} 
?>
```

Do you give me your opinion?
I've been stuck here for 5 days and I can not understand what I'm missing.
The assistance of Coinbase does not answer me and I have a project to deliver blocked.

Thank you very much for any useful advice.
