### ISSUE TITLE
Poloniex nonce issue

### ISSUE THREAD

**Issue by ezhik97** [timmolter/XChange#1193]
Sometimes PoloniexTradeService.getOpenOrders() throws exception like:
`si.mazi.rescu.HttpStatusIOException: Can not deserialize instance of com.xeiam.xchange.poloniex.dto.trade.PoloniexOpenOrder[] out of VALUE_STRING token at [Source: java.io.StringReader@4179bd37; line: 1, column: 2]`

Debugging says, that poloniex return http body like:
`{"error":"Nonce must be greater than 396283927. You provided 396282554."}`

The hot fix is to catch such errors and create new Exchange object for poloniex. After that the system works fine for some time.

**Comment by timmolter** [comment]
Are you multithreading by chance? That could cause the issues.

**Comment by ezhik97** [comment]
Yes. Is there a chance to fix that?

**Comment by abelgo** [comment]
I have the same issue. multi threading of course,  The only fix I have is to do a scheduled hard reset every hours or so.

**Comment by timmolter** [comment]
Yes, you can define the NonceFactory you want to use when you create the Exchange object. I believe there are a couple of thread safe ones you could try. Look in `core` to see which ones are available.

**Comment by ezhik97** [comment]
My fix is nearly the same - recreate thread executor (with exchange) in case of 2 http exceptions, because I can't wait so long time.

**Comment by ezhik97** [comment]
timmolter, thanks. will try.

**Comment by abelgo** [comment]
I did take a look at the NonceFactory, as far as I could tell the default one Poloniex uses should be thread safe. I also wrapped a few synchronized blacks around some critical sections, However still got the problem. Was thinking that it might be Poloniex but did not confirm that yet.

**Comment by ezhik97** [comment]
@abelgo , yes, I also looked thru sources and found that default nonce factory must be thread safe.

**Comment by timmolter** [comment]
Hmmm, yes the default one is thread-safe. Must be some other issue.

**Comment by hems** [comment]
i'm not using this project but i'm getting the same error from PLNX when firing multiple requests, even without multi-threading.

i believe the must be something about firing a few requests close in time and plnx getting them in the wrong order, or some requests taking to long to reach them while others magically happens quick.

there is something funny there, because sometimes the requests will also timeout, which means they might not be exactly ready for loads of API calls.

**Comment by hegjon** [comment]
I run into the same issue getting `Nonce must be greater than 1441530791414. You provided 406231706.`, I might have used their API a while ago with another library.

**Comment by ezhik97** [comment]
Because difference between your values too much I guess that your API key had been used from another system.

**Comment by hegjon** [comment]
It seems like the nonce factory is hard coded to AtomicLongIncrementalTime2013NonceFactory and I can not find a way to reset the nonce on Poloniex. I will create another issues, since this is a new feature.

**Comment by hegjon** [comment]
Created #1214

**Comment by mmazi** [comment]
I think the safest nonce factory to use for 32-bit nonces is `TimestampIncrementingNonceFactory` -- for an argumentation see eg. #851 . (It's not 100% bullet proof, but that's because of issues inherent to HTTP APIs and the limitation of 32 bits.)

(This is when 32-bit nonces are required; with 64-bit nonces, a simple millisecond timestamp (`CurrentTimeNonceFactory`) is simpler and better.)

I changed Poloniex impl to use `TimestampIncrementingNonceFactory` by default in ca17be639. Please report if this behaves any better. (The new nonce factory will produce larger nonces than the previous one (unless you've been constantly making more than 4 requests per second) so the same API keys should continue working.)
