### ISSUE TITLE
Margin Lending Support

### ISSUE THREAD

**Issue by abelgo** [timmolter/XChange#1231]
Do we have any thing that supports this at the moment. ?  
So we have sort of support for exchanges whit more than one wallet in AccountInfo, But then in the PolingAccountService we don't have and calls in the interface to do transfers between different wallets.

I saw the dto for LoneOrders but not sure that is usable with the PolingTradeService at this point ?

**Comment by douggie** [comment]
okcoin support futures but this is handeled a little differently by the exchange as okcoin treats them as a seperate product within the same account.

Margin trading on other exchange support the same product funded from a different 'margin account'

Keen to get this working for poloniex.

Not sure what Tim thinks but may be something along the following lines

1) add a flag to the order type like 'marginFunded' in the order interfaces that will tell the exchange implementation to place a margin trade such as marginBuy on poloniex rather than just a buy.

marginBuy
Places a margin buy order in a given market. Required POST parameters are "currencyPair", "rate", and "amount". You may optionally specify a maximum lending rate using the "lendingRate" parameter. If successful, the method will return the order number and any trades immediately resulting from your order. Sample output:

{"success":1,"message":"Margin order placed.","orderNumber":"154407998","resultingTrades":{"BTC_DASH":[{"amount":"1.00000000","date":"2015-05-10 22:47:05","rate":"0.01383692","total":"0.01383692","tradeID":"1213556","type":"buy"}]}}

rather than a normal buy
buy
Places a limit buy order in a given market. Required POST parameters are "currencyPair", "rate", and "amount". If successful, the method will return the order number. Sample output:

{"orderNumber":31226040,"resultingTrades":[{"amount":"338.8732","date":"2014-10-18 23:03:21","rate":"0.00000173","total":"0.00058625","tradeID":"16164","type":"buy"}]}

2) add additional methods to account interfaces to support methods to move, add, withdrawal from margin account.

**Comment by timmolter** [comment]
Feel free to add any functionality you'd like at the "Raw" level. If it's commonly used across multiple exchanges, we can talk about adding it tot the "generic" level.

**Comment by douggie** [comment]
Hi Tim,

Quite a few exchanges support the concept of 'lending' a balance for your
to trade with, aka margin.

here are a couple I am aware of.

*bitfinex*
https://www.bitfinex.com/pages/howitworks
*poloniex*
https://poloniex.com/support/aboutMarginTrading/
*Kraken*
https://support.kraken.com/hc/en-us/sections/200560633-Leverage-and-Margin

Do you think it would make sense to add it at the 'genric' level given it
is quite widely supported?

Happy to think through the implementation details and provide a proposal
for your review.

**Comment by timmolter** [comment]
Yes, I think it's a possible candidate. First you should create PRs for the Raw implementations. Then create a PR for the generic implementation. That's the best and most efficient way to show it working.

**Comment by douggie** [comment]
As always Tim! 

Douggie Melville-Clarke
+44 7825 817575
douggiem@traiana.com

**Comment by douggie** [comment]
Hi Tim,

Been a bit busy, was thinking about this the following day. How about an implementation like ok coin:

1) create new class org.knowm.xchange.poloniex.service.polling.PoloniexMarginTradeService.java
1) add exchange specific parameter called margin
2) instantiate poloniex with use_margin=true
3) when poloniex is instantiated with use_magin it will use the PoloniexMarginTradeService implmentation.

**Comment by byronvoorbach** [comment]
Hey @douggie & @npomfret!

**Comment by timmolter** [comment]
@byronvoorbach I don't think anyone is working on it or planning to. I would consider making a new `Service`, `LendingService` if you committed to filling in a handful of implementations. How many exchanges are you working with that offer margin lending anyway? Which ones besides Poloniex?

**Comment by dave0688** [comment]
I'd be interested in a lending service as well.

**Comment by douggie** [comment]
Hi Tim,

think we can close this as it was comitted in #1231.
