### ISSUE TITLE
Poloniex API needs to use USDT, not USD

### ISSUE THREAD

**Issue by PoCk3T** [timmolter/XChange#1372]
Hi everyone,

First, congrats to the original author and all contributors for this amazing project :)

Now, trying to get Poloniex ticker for CurrencyPair.BTC_USD results in error, even with latest 4.2.0 SNAPSHOT version of Xchange.

Indeed, Poloniex is using USDT, not USD, as pointed out by @mmazi  in https://github.com/timmolter/XChange/pull/1254 

Should I implement a workaround in my own code or is there any kind of 'currency translation' that could be done in Xchange Poloniex code to accomodate that exchange specificity ?

Thanks :)
Lucas

**Comment by mmazi** [comment]
Hi @PoCk3T ,

USD and USDT are two entirely different currencies: USDT does not refer to the US Dollar but rather to [Tether](https://tether.to/). The exchange rate between USDT and USD does tend to stay around 1.0 by design, but that doesn't make them the same currency, just as AUD was never considered the same currency as USD even tough it has reached 1.000 exchange rate with USD in the past.

(Please note that it is possible that the USDT/USD rate diverges from 1.00, eg. if the company behind Tether gets hacked or shut down by authorities etc.)

So the fact that Poloniex uses USDT and not USD stems from their choice of currencies (they don't deal with fiat currencies at all; USDT is a crypto-currency) and is a completely different thing from, for instance, the fact that some exchanges use of XBT and others BTC to denote bitcoin where a simple mapping/translation is appropriate.

> CurrencyPair.BTC_USD results in error

This is correct behavior in XChange as Poloniex does not deal with USD.

> Should I implement a workaround in my own code 

Depends on what you are trying to achieve. I wouldn't recommend treating USDT rates as the same as USDT rates though.

**Comment by PoCk3T** [comment]
Thanks for the fast answer @mmazi 

I understand better now.

Still, technically speaking, wouldn't it be relevant to add USDT as a standalone currency in Xcode code, as well as BTC_USDT as a CurrencyPair ?

So users of Poloniex can still use Xchange in order to get tickers, etc etc ?

What do you guys think ?
If yes, what's the best way ? Should I fork Xchange, commit these enhancements, and submit a pull request ? (sorry for the naive question, it would be my first time doing so :))

**Comment by mmazi** [comment]
You can always use `Currency.getInstance("USDT")` (or simply `new Currency("USDT")`) and similarly `new CurrencyPair(...)` in your code.

As for adding USDT to the list of built-in currencies, I'll leave this for @timmolter to decide.

**Comment by timmolter** [comment]
yes, a pull-request for it would work well.

**Comment by datasmithtech** [comment]
I apologize if this may seem obvious, but where may I find a configuration file which the application uses to initialize the Exchange upon startup?

**Comment by timmolter** [comment]
src/main/resources

**Comment by jheusser** [comment]
This might have been addressed now?

**Comment by timmolter** [comment]
yes, addressed.
