### ISSUE TITLE
High Priority one! BitfinexOrderStatusResponse cannot handle the ID returned by the exchange.

### ISSUE THREAD

**Issue by kisapmata** [timmolter/XChange#1430]
This is quite a big issue. Since march 24, order ID generated by Bitfinex is > Integer.MAX_VALUE. This means, orders are executed on the exchange but we cannot process the response due to json parsing exception. This puts the user at risk in many ways like hedging and trade reconciliation as the user doesn't even know that he just executed an order. Please note that this can happen to all the Exchange Packages that uses INTEGER for ID instead of LONG or whichever is appropriate.

**Comment by kisapmata** [comment]
forgot to mention that this impacts also order cancellation and retrieval of order status etc.... anything that references to the order id.

**Comment by jheusser** [comment]
already fixed in develop. please pull latest version before reporting
issues.

On 7 Apr 2017 7:35 am, "kisapmata" <notifications@github.com> wrote:

forgot to mention that this impacts also order cancellation and retrieval
of order status etc.... anything that references to the order id.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/timmolter/XChange/issues/1430#issuecomment-292453849>,
or mute the thread

**Comment by kisapmata** [comment]
i see. gotcha. I've been having problem syncing my forked version recently so I missed out this changes. But I have to say that Bitstamp (and others) is going the same path but is not critical at this moment.

**Comment by kisapmata** [comment]
closing this issue
