### ISSUE TITLE
Bittrex getTicker() fail with exception

### ISSUE THREAD

**Issue by ezhik97** [timmolter/XChange#1591]
Today I've updated to develop snapshot and realize that BittrexMarketDataService.getTicker(pair) stop working with exception:

`si.mazi.rescu.HttpStatusIOException: Instantiation of [simple type, class org.knowm.xchange.bittrex.v1.dto.marketdata.BittrexTickerResponse] value failed: null (through reference chain: org.knowm.xchange.bittrex.v1.dto.marketdata.BittrexTickerResponse["result"])
	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:104)
	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:169)
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:157)
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:120)
	at com.sun.proxy.$Proxy19.getTicker(Unknown Source)
	at org.knowm.xchange.bittrex.v1.service.BittrexMarketDataServiceRaw.getBittrexTicker(BittrexMarketDataServiceRaw.java:58)
	at org.knowm.xchange.bittrex.v1.service.BittrexMarketDataService.getTicker(BittrexMarketDataService.java:41)`

**Comment by SeanRobb** [comment]
I also was seeing some issues when retrieving the Bittrex ticker.  I looked in to recent developments and there looks like there was a pull request 5 days ago that flipped the base and counter values in the currency pair.  I have switched them back and verified that my ticker issue is gone locally.  I now have a [pull request](https://github.com/timmolter/XChange/pull/1592)  waiting to get merged. Hopefully it will fix your issue as well.

**Comment by ezhik97** [comment]
Yes, it is fixed this issue to. Very strange logic was added.

**Comment by timmolter** [comment]
I merged your overriding PR. I agree that that previous PR broke it.

**Comment by npomfret** [comment]
Apologies for the break.  The reason I made the change was because you can place trades on bittrex using the _common_ pair `BTC/XRP` for example, but when you get the trade history is comes back as `XRP/BTC`.  I was trying to make the API more symmetrical.

I realise now that maybe that wasn't the right thing to do.  It's up to the user to understand that this exchange represents certain currency pairs differently to most other exchanges.

There doesn't seem to be any pattern to how exchange represent these markets.  For example, t=with RXP and BTC:

bitstamp, hitbtc and kraken all call it XRP/BTC
and
bittrex, poloniex and therocktrading call it BTC/XRP

More confusingly, they all have roughly the same price, except for therocktrading, which has the reciprocal price.

How do people normally deal with this problem?

**Comment by ezhik97** [comment]
In that example BTC is the market, XRP is the currency.
The "standard" pair is: "currency/market". Some of exchange services represent that on UI in reverse order - market/currency. But - the list of available pairs you can get via API, and there they use standard format 'currency/market'.

**Comment by npomfret** [comment]
Most do, but not all. therocktrading for example, i'm sure there are others
