### ISSUE TITLE
Set proxy for single Exchange instance

### ISSUE THREAD

**Issue by PIBODIBU** [timmolter/XChange#1640]
I have problem with Poloniex API. Every request is 403 Forbidden, because stock responses with blank screen with captcha instead of JSON data.
I have discovered the problem is connected with my IP, because services like "cURL online" fetched data successfully.
So, my question: 
**How can I set proxy settings for single Exchange instance?**

**Comment by douggie** [comment]
Hi, you can add a proxy via rescu.properties but this will effect all
connections. If you just want a subset of ips via a proxy probably best to
add a static route (route add) to just route given destination ips to the
proxy. You might need to set ip tables masqureding on the proxy  (
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/4/html/Security_Guide/s1-firewall-ipt-fwd.html)
so that your xchange host does not think it is talking to a proxy.

Regards

**Comment by archenroot** [comment]
@dougle - so exchanges otherwise block proxied connections? So if my application is in production env without direct network connectivity and I have to use nginx or other proxy, it wont work with Exchanges?
