### ISSUE TITLE
Java version

### ISSUE THREAD

**Issue by cymp** [timmolter/XChange#1680]
I couldn't find in the wiki which Java version we should use for coding and I think this is Java 7. What do you think about migrating to Java 9 once it is officially out?

**Comment by timmolter** [comment]
I'm more included to keep it at Java 7 because it will allow more people (who may be forced to use an old version) to be able to use XChange. You can use Java 9 runtime to run it, and in the Maven pom.xml file Java 7 is defined, so IDEs like Eclipse and intelliJ will automatically use a Java 7 compiler, even if you have the Java8 or 9 JDK in use and no Java 7 installed on your system at all.

**Comment by cymp** [comment]
Okay, I am just a bit frustrated to not be able to use lambdas and other Java 8+ stuff.

**Comment by timmolter** [comment]
Also people use this as a basis for Android apps, and last time I checked, Java 8 was not supported.
