### ISSUE TITLE
open orders: tradableAmount

### ISSUE THREAD

**Issue by npomfret** [timmolter/XChange#1714]
I know this question was discussed recently but I can't find it, sorry.

What is the `tradableAmount` field _supposed_ to represent in a open order?  I guess it could be any of:

 * the original order size (before any fills happened)
 * the current order size (the original minus the total quantity filled already), aka _amountRemaining_
 * the amount filled already, aka _amountFilled_

**Comment by cymp** [comment]
I am 99% sure it is not the _amountFilled_ already, from what I observed in my software.
My understanding is that it corresponds to the _amountRemaining_.

**Comment by MartianTech** [comment]
This has been creating inconsistency across exchanges. I propose we change them to 
```
private final BigDecimal originalAmount;
private final BigDecimal remainingAmount;
private final BigDecimal executedAmount (or filledAmount);
```

**Comment by timmolter** [comment]
@MartianTech I think that's a great idea.

**Comment by npomfret** [comment]
+1 for this.  Big change though.

I'd prefer to name the 3rd one `filledAmount`, that's the terminology I'm familiar with from working in finance.  I think _executedAmount_ could be mistaken for _originalAmount_ by some.

**Comment by timmolter** [comment]
I like `filledAmount` better as well. We can keep the existing getter and setter (but delete the field) and just set/return whatever field we think is the standard one, in addition to the new three.

**Comment by Achterhoeker** [comment]
This is what i've already started with. See https://github.com/timmolter/XChange/issues/1693
I'll add an getter for filledAmount (doesn't need a field, it can be calculated from originalAmount and remaining amount)
I'll also rename the current amount field to original amount and maintain the getter/setter for it.
But the problem is time to do this. Next Wednesday is the first day i have some spare time for this.

**Comment by timmolter** [comment]
deprecated `getTradeableAmount` also now removed.
