### ISSUE TITLE
Questions regarding Exchange and Service's states and lifecycle

### ISSUE THREAD

**Issue by MartianTech** [timmolter/XChange#1729]
Let's say we have the following code in my class.
```
this.exchange = ExchangeFactory.INSTANCE.createExchange(this.exchangeSpecification);
this.marketDataService = this.exchange.getMarketDataService();
this.accountService = this.exchange.getAccountService();
this.tradeService = this.exchange.getTradeService();
```
If I pass around the references to other classes, do I need to handle any synchronization or inconsistent state issue across classes when using these services? 

Basically, I want to know during my program's lifecycle, is it safe to assume I only need to create one instance of Exchange and pass its reference anywhere without worrying about any internal inconsistency? 

Am I correct to assume so because it's REST API so instance of Exchange doesn't hold any internal state information and it's just a set of interfaces. 

Assuming the exchange specification is the same, does it mean, in no circumstance, that I need to recreate the instance of exchange and its services in case of exceptions? Once they are created, they are always valid to use? 

Let me know if my questions are ambiguous and I'd structure them more clearly.

**Comment by npomfret** [comment]
The services are all stateless, you need to manage state yourself. You can pass around instances of the exchange object, or create new ones.

The problem comes with exchanges that use a nonce value.  In which case you should just have one instance of the exchange object, and pass it round.  Some exchanges let you create multiple API keys which allows the developer to create multiple instances of the exchange objects, but only one per API key.

**Comment by MartianTech** [comment]
So as long as I only create one instance of exchange and pass around, I don't need to worry about nonce value or API keys?

**Comment by npomfret** [comment]
Yes.  Err... mostly.

The problem with the exchanges that use a nonce is that you basically can't have any concurrent calls to the exchange, so no multi-threaded access, no multi-program access.  You can only issue one http request at a time.  Usually, this restriction only applies to the private APIs (the account service and trade service) because the public API calls (the market data service) often don't use the nonce.  If you submit concurrent http calls they could _overtake_ each other on the way to the server so the nonce can effectively become corrupted and all but one of the calls might fail.

If you want multi threaded access you could either create multiple api keys if the exchange allows it (most do, Bleutrade doesn't but I don't know of any others).  Or you could do something _clever_ with a mutex block to ensure there's only a single api call happening at any one time.

**Comment by MartianTech** [comment]
What would be considered concurrent http calls? Does that mean making a call before the first call return, or there is a timeframe threshold that two calls are made within? 

To make sure multi threaded access working properly, what object would the mutex be placed on?

**Comment by npomfret** [comment]
That's right.  You have to wait for each call to finish to be sure that it's reached the exchange (or failed).

Take a look at `Mutex` (or semaphore) https://www.mkyong.com/java/java-thread-mutex-and-semaphore-example/

**Comment by MartianTech** [comment]
Thanks a lot!

**Comment by npomfret** [comment]
I guess the final thing to mention is that when using a mutex you need to make sure that which ever process _has_ the mutex will eventually give it up.  This is especially worth considering when accessing http resources inside the mutex....  What happens if the server is slow to respond, or maybe never responds (and doesn't close the connection or throw an error).  Then your program will never make another http call ever again.

The solution is to unsure that your http call will timeout eventually.  There are some instructions on here (somewhere) about configuring timeouts.  But I'm not sure they're complete.  There's more than one http timeout to worry about - you have at least 2 (maybe more?):

* The socket timeout (how long do you wait for a connection to the server)
* The read timeout (how long do you wait after the socket connection is made for the response)

At the very least you need to make sure that both of these values have a non-infinite setting.

**Comment by MartianTech** [comment]
These are great information. I'd take a look and follow up with you. Would it be possible to integrate this synchronization mechanism into the library? It seems pretty generic and doesn't depend on specific exchange implementation.

**Comment by MartianTech** [comment]
@npomfret In the previous comment, you brought up two great points. 
```
The socket timeout (how long do you wait for a connection to the server)
The read timeout (how long do you wait after the socket connection is made for the response)
```
I didn't really differentiate these two exceptions before but do you think I can deal with them like the following - 
socket timeout: my last request did not reach to server at all and I can resend the last request. If I were to place an order, I can assume it didn't make it to the order book and safely place it again. 

read timeout: connection was established but server didn't return before timeout. My request may or may not have been processed.  If I were to place an order, I need to check if this order has been placed on order book or not before deciding to replace it or not. 

Is my understanding correct?

**Comment by MartianTech** [comment]
Also, what does `ExchangeSpecification.setHttpReadTimeout` set, socket or read timeout or both?

**Comment by npomfret** [comment]
Sorry for slow reply, have been away.

Yes, idempotent operations (read only stuff typically) can just be re-retried safely, but anything else must not be without consideration.  So if you aren't able to make the initial socket connection you can be sure it's safe to re-try any operation.  But, if the operation encounters a timeout whilst reading the response you need to be more careful - your understanding is correct.  This goes for any http rest-style operation and is nothing specific to this library.  Distinguishing between the two is important if you want to incorporate any re-try logic.

I believe the way to configure you app is to have something like this in your _rescu.properties_ file in the root of your class path:

```
rescu.http.connTimeoutMillis=1000
rescu.http.readTimeoutMillis=24000
```

Unfortunately I don't believe that this project supports _generic_ per-exchange http config, which would be nice.  The `ExchangeSpecification.setHttpReadTimeout` appears to only be supported on an ad hoc basis, only Kraken and Poloniex appear to have implemented it.

Finally, some http clients can auto-retry idempotent operations (`GET`, `PUT`, `DELETE`, `HEAD`) for you, but I don't know much about this _rescu_ library we're using.  Retry logic may already be handled...?

**Comment by MartianTech** [comment]
@npomfret Hey Nick, thanks for your reply. It's very helpful. Can you let me the two exception types that I can use to differentiate? So we have SocketTimeoutException for connTimeoutMillis. What would be for the readTimeoutMillis?

**Comment by npomfret** [comment]
I don't know the exact exceptions but you can force them to happen by setting the two timeout values to 1ms.  Obviously, you'll need to do them one at a time because the read timeout won't happen if the connection isn't made.

**Comment by jcuypers** [comment]
it would be beneficial if this could be integrated with the rate-limiter discussion.  mutex block with rate-limiting consideration.
