### ISSUE TITLE
Truncated List<FundingRecord> on Kraken

### ISSUE THREAD

**Issue by Xion345** [timmolter/XChange#1820]
**Issue Description**
When retrieving funding history, the returned List<FundingRecord> omits some funding events (the oldest ones).

**How to reproduce**

    Exchange krakenExchange = ExchangeFactory.INSTANCE.createExchange(
        KrakenExchange.class.getName());
    krakenExchange.getExchangeSpecification().setApiKey("API KEY");
    krakenExchange.getExchangeSpecification().setSecretKey("SECRET");
    krakenExchange.applySpecification(krakenExchange.getExchangeSpecification());

    AccountService service = krakenExchange.getAccountService();
    TradeHistoryParams params = service.createFundingHistoryParams();
    for (FundingRecord record : service.getFundingHistory(params)) {
        System.out.println(record.getCurrency() + " " + record.getType() + 
            " " + record.getAmount());
    }

**Discussion**
I think the issue is ultimately due to a lack of clarity in Kraken's API documentation (cf. https://api.kraken.com/0/private/TradesHistory). Although, it is not explicitely mentioned in the API documentation, Kraken appears to return only the latest 50 events. Therefore, to obtain the full list of events, it is necessary to iterate using the 'end' parameters until no event are returned.

I am going to (try to) implement this. My only question is: is it a bug or a feature ? Is it expected behavior for XChange to return only the n last events (if so, it should be mentionned in the documentation), or is it a bug ?

**Comment by npomfret** [comment]
Sounds like a bug.

Are funding events returned via the `TradeHistory` call?  If so it might be difficult to implement.

The problem could be that the xchange API internally calls `TradeHistory` in order to get funding events.  The most recent 50 items that are returned are all trades and get filtered out.  So the user see's an empty list returned (because that's all the xchange api is currently set up to respond with).  So basically you do a `fundingHistory` call, and nothing comes back, and there's no prompt in the returned object to tell you to make another call.

This api maybe needs a paged response, or something similar, that has the information to prompt the user to make another call even though no data was returned.

@timmolter i don't know if i'm being very clear here (sorry, got a new puppy and my brain is not working very well).  Do you understand the issue I'm describing?

**Comment by jcuypers** [comment]
According to me this is similar to the behavior of gettradehistory.  It has also a limitation of 50 transactions.   like @timmolter explained you need to page the results by specifying and incrementing an offset.   A quick test just now solved the same problem for me.   please be aware that you still need to respect the API limits otherwise you will get locked out for 15min.  You can filter the request more but you need to look in the source code what is supported.  for tradeservice only time and offset is supported as far as i quickly checked.

            TradeService tradeService = kraken.getTradeService();

            TradeHistoryParams params = tradeService.createTradeHistoryParams();
            if (params instanceof TradeHistoryParamsTimeSpan) {
                final TradeHistoryParamsTimeSpan timeSpanParam = (TradeHistoryParamsTimeSpan) params;
                timeSpanParam.setStartTime(new Date(System.currentTimeMillis() - (1 * 12 * 30 * 24 * 60 * 60 * 1000L)));
            }
            if (params instanceof TradeHistoryParamOffset) {
                final TradeHistoryParamOffset offset = (TradeHistoryParamOffset) params;
                offset.setOffset(50L);
            }

            trades = tradeService.getTradeHistory(params);

**Comment by Xion345** [comment]
Yes, you are right that the Kraken API limits the number of ledger entries returned to 50 per API call. I think that `getFundingHistory(...)` should however iterate over pages and return all funding history, i.e., the user should not need to implement pagination (or else it should be mentioned in the documentation)

I have a working prototype of an implementation of `getFundingHistory(...)` which iterates on pages by decreasing `end` date until no entries are returned. I don't know if this is the appropriate way to do it, but I am able to retrieve my full history this way (255 entries). I am polishing the formatting and the Javadoc. I will do a pull request later this night so that everyone can have a look at it and suggest changes.

**Comment by jcuypers** [comment]
great to hear it's working. the offset would be more universal and is specifically for this purpose.  Anyway, if it works, great.

**Comment by Xion345** [comment]
Got it working using the offset parameter, instead of the end parameter. You were right, it makes the code simpler, so it's all good.
