### ISSUE TITLE
Coinbase ETH/USD wrong value

### ISSUE THREAD

**Issue by BerndGit** [timmolter/XChange#1856]
I got the following Ticker from Coinbase for ETH/USD:

Ticker [currencyPair=ETH/USD, last=6448.22, bid=6413.22, ask=6480.46, high=null, low=null,avg=null, volume=null, timestamp=null]

this is too good to be true. seems to be BTC/USD values.

**Comment by npomfret** [comment]
I think the coinbase implementation is a bit broken.  Use the GDAX one instead.

@timmolter is there any value in keeping the coinbase code?

**Comment by timmolter** [comment]
I think we should remove it, as no one seems to be maintaining it. I assume most people use the GDAX impl.

**Comment by Xion345** [comment]
I don't think this is a bug in the implementation because I use a desktop applet which reports exchange rates from Coinbase and it was returning false values the last days. It has returned to normal about 12-24 hours ago or so. So my conclusion is that it was a transient issue on Coinbase side, and I would advise -- if everyone agrees -- to close the issue.
