### ISSUE TITLE
Always create new exchange in multi thread environment?

### ISSUE THREAD

**Issue by nihiluis** [timmolter/XChange#1928]
when im in a multi thread environment, i.e. dealing with a rest request, should I always create a new exchange or use the existing exchange?

```kotlin
    val gdax = ExchangeFactory.INSTANCE.createExchange(GDAXExchange::class.jvmName)
    val service = gdax.marketDataService
    val ticker = service.getTicker(CurrencyPair.BTC_USD)
```

**Comment by digitalchaotics** [comment]
You can reuse the exchange instance, but you should take steps to ensure that only one thread is active through the exchange at any given time.  More than one instance won't help you that much, because the rate limits on the exchange's servers will shut you down.  Better to put put each call in a synchronized block, with the sync object being the exchange itself.  (I have a wrapper class that proxies the exchange methods, so I put it there.)  Making the exchange synchronized will guarantee that only one thread is active at a time, but you still have to be careful about rate limits.

**Comment by nihiluis** [comment]
this doesnt sound good when Im handling http requests, quite some overhead. is there less overhead when I just create one?

**Comment by digitalchaotics** [comment]
Unless you have separate exchange accounts (and keys), the rate limits on the server will be your primary throttle.  The best you'll get is one or two requests per second, as an average rate.  Some of the exchanges require you to be slower - much slower.  The overhead of wrapping REST calls in a synchronized block will be negligible.

I haven't tested it, but I'll bet some of the exchanges also impose rate limits per IP address, so having extra keys won't help.  If it were my server, I would do that, too.
