### ISSUE TITLE
References/examples for building live feed

### ISSUE THREAD

**Issue by nitzanav** [timmolter/XChange#1977]
Hi,

Thank you for this awesome project! It is amazing!

I want to build a live feed of crypto currencies order book, maybe using a deamon that is similar to what was done in [bitcoinium.com](https://github.com/veken0m/bitcoinium/blob/a60fee461405174ef82bcca89fefcb430baeb368/src/main/java/com/xeiam/tasks/GeneralUpdateDeamon.java#L25) just with sub seconds(100ms is great) pulling time interval.

I want to describe to you my plan and ask for additional references or tips. 

So my plan is:

1. Loop for forever each exchange and symbol
2. If it has WebSocket Api, use [xchange-stream](https://github.com/bitrich-info/xchange-stream) otherwise use REST with [XChange](https://github.com/timmolter/XChange).
3. Retry with some exponential backoff sleeping when  you have a connection error or reached an API rate limit. Like in the [RetriesDemo](https://github.com/timmolter/XChange/blob/0af6279f52d779b324dfce4f4a710952e2ccb166/xchange-examples/src/main/java/org/knowm/xchange/examples/core/utils/RetriesDemo.java). I Guess that I will need to form IPredicate for each exchange, did anyone do it so far?

I would be happy to get input if people here think that my plan is correct and be shared with references of code any relevant example.

What is the right place for such questions?

**Comment by jcuypers** [comment]
the websocket part is fine. although you might want to try an api which aggregates streams from many exchanges instead of having to maintain a websocket for each specific one.  also sometimes the exchange support is better than the individual ones you are integrating yourself.   regarding the REST calls.   You will never get to the sub-second behavior as (like you indicated yourself), they will impose limitations on how many calls per x seconds you can make.  also... some support many symbols in 1 call, others don't.  The mechanism you need to develop to make everything run smoothly is way overkill (in my opinion). Also any additional logic / functionality you want all depends on the frequency your data can come in... (let's suppose alarms) I wouldn't waste your time on this part to be honest.   just reserve this for the trading part if any. (or some specific data you might need to fetch in case not available elsewhere.

If I were you, I would find a webservice/socket.io stream, use rxjava to react on incoming updates and take it from there to do anything you need to do.

**Comment by nitzanav** [comment]
Thank you @jcuypers !
