### ISSUE TITLE
[all] Adding Fills as first class objects in the API

### ISSUE THREAD

**Issue by bryantharris** [timmolter/XChange#2454]
Thoughts on adding `Fills` to the API?  The value is greater with the web sockets, but many of the APIs I've seen allow you to obtain the fills for a trade.

I'm happy to put something together if the idea is well received.

**Comment by michaelscheung** [comment]
One example of this is GDAX, which has [get order](https://docs.gdax.com/#get-an-order) and [get fills](https://docs.gdax.com/#fills). Currently, `TradeService.getOrder` is documented as `get's the latest order form the order book that with matching orderQueryParams`. However, in GDAX, it seems to be using the get orders API, which also returns completed orders. So either the documentation in `TradeService` is wrong (since this order is no longer on the order book), or the implementation is wrong. `GDAXTradeService.getTradeHistory` uses the fills API.

It does seem like `UserTrade`, which is returned by `getTradeHistory`, is currently being used for fills. In particular, it has both an order ID (to reference the original order) and an ID (to reference the fill/transaction ID). Would it be sufficient to just use the `UserTrade` object for fills, as we are already doing for GDAX (and possibly others)?

**Comment by bryantharris** [comment]
Oh I didn't realize UserTrade was the fills.  Yeah if there's something in place, I don't care what its called.  My main reason was really on the web socket side, I want to receive the fills in real time off the websocket but needed an object for that.

I'll use UserTrade, thanks.
