### ISSUE TITLE
Proposal to remove `tradingFee` from `AccountInfo`

### ISSUE THREAD

**Issue by timmolter** [timmolter/XChange#838]
With exchanges getting more and more feature rich, a simple `trading fee` is almost never enough. Sometimes, it is currency dependent or dependent on if you're providing or taking liquidity.

I propose moving this field to our newly-created `TradeMetaData` DTO via the TradeService. It's tied to individual currencies via a map in the call `getTradeMetaDataMap()` in `PollingTradeService`. There is also a mechanism in place to load the `TradeMetaData` DTO via a properties file because sometimes it's not available via an API call from the exchange.

I'm going to do this refactor unless I hear a massive uproar against it.

**Comment by rafalkrupinski** [comment]
Since you mentioned maker/taker fee policy, from what I found, fees can be tied to one or more of:
- market
- trading volume
- order type - market or limit (I only know that ANX does that)
- adding or taking liquidity

We would have the first two addressed. Would you provide any support for no.3?
To address the liquidity, you would have to provide two methods, but on the other hand, you can be never sure which fee you're going to pay. getMaxFee() maybe?

**Comment by timmolter** [comment]
Thanks for the feedback. Yes, as long as we can get in inside the TradeMetaData in some way, it should be supported.
