### ISSUE TITLE
single com.xeiam.xchange.Exchange for each futures contract for OKCoin

### ISSUE THREAD

**Issue by douggie** [timmolter/XChange#971]
Hi,

Currently with OKCoin futures, the contract to be traded is set at the exchange specification, requiring 4 different exchanges to trade the week, nextweek, month and quarter contract, given the need to roll each friday from the weekly to the next week contract, it would be nice to be able to have one okcoin com.xeiam.xchange.Exchange instance for all contracts.

**Comment by jheusser** [comment]
I don't think that would lead to a good solution. This is mainly because contracts are not currency pairs, and normal instantiation of OkCoin is for spot trading (like all of XChange). Passing in contracts through varargs (or anything through varargs actually) leads to very ugly and unstable code in my opinions. Then you have to check inside the method whether the adapter is configured to be for futures (easier to misconfigure like that), check runtime types of objects etc. I would rather like to avoid passing them in through varargs.

Btw, apart from that, you can keep trading `ThisWeek` even on contract expiry time. So `ThisWeek` will always point to the latest early-expiry contract.

**Comment by douggie** [comment]
ah okey cool, I did not know that, I thought I need to roll, so can just sell this week, then after 8am on Friday settlement LN buy it again.
