### ISSUE TITLE
Rescu not producing an exception for an error that is sometimes returned from Bitso

### ISSUE THREAD

**Issue by bryan4887** [timmolter/XChange#987]
If you poll the orderbook API of Bitso too frequently, it will return:
`{"error":{"code":200,"message":"Too many requests"}}`

This seems to confuse the BitsoOrderBook constructor because the returned json (above) does not contain the properties it expects:
```
public BitsoOrderBook(@JsonProperty("timestamp") Long timestamp, @JsonProperty("bids") List<List<BigDecimal>> bids,
                           @JsonProperty("asks") List<List<BigDecimal>> asks) {

    this.bids = bids;
    this.asks = asks;
    this.timestamp = timestamp;
  }
```

As a result, the returned instance of `BitsoOrderBook` has `null` values for bids, asks, and timestamp.  What I believe should happen instead is that this error json should be parsed correctly, and then pass along a `HttpStatusIOException` even though the response code is 200.  That way, the calling method can wait for a few seconds and try again.

I'm not familiar with how Jackson works, but I believe all that needs to change is the constructor of BitsoOrderBook, right?  Something like this:

```
  public BitsoOrderBook(@JsonProperty("timestamp") Long timestamp, @JsonProperty("bids") List<List<BigDecimal>> bids,
                           @JsonProperty("asks") List<List<BigDecimal>> asks, @JsonProperty("error")  SomeType error) {
```

The only problem I'm having is that I can't figure out what `SomeType` should be.  I've tried `String` or `List<String>`, but everytime I get: 
```
si.mazi.rescu.HttpStatusIOException: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: {"error":{"code":200,"message":"Too many requests"}}; line: 1, column: 2]
```

So I'm clearly doing something stupid.  

Can anyone suggest how best to handle these errors?

**Comment by timmolter** [comment]
I think you need to create a DTO called `BitsoError` which has an int and a String as members and use that as `SomeType`.

@mmazi What would you recommend in this case?

**Comment by mmazi** [comment]
@bryan4887 , it works in a bit different way, even simpler -- the exception simply needs to be declared on the interface, this should do it: https://github.com/timmolter/XChange/pull/993

The exception class and the DTO are completely decoupled. You can read more about exception creation in rescu [here](https://github.com/mmazi/rescu/wiki/Exception-handling).

Note that the Exception class is normally just a simple Jackson-annotated class that maps to json directly; there is some complexity in BitsoException (that is not normally needed) because Bitso returns two json formats for different errors.

**Comment by timmolter** [comment]
@mmazi Thanks. I had a feeling I was forgetting something.

**Comment by bryan4887** [comment]
@mmazi Thanks.  I pulled your changes, but something is still missing.  You can test it by running this code:
```
public static void main(String[] args) throws ExchangeException, NotAvailableFromExchangeException, NotYetImplementedForExchangeException, IOException {
		Exchange exchange = ExchangeFactory.INSTANCE.createExchange(BitsoExchange.class.getName());
		PollingMarketDataService service = exchange.getPollingMarketDataService();
		CurrencyPair cp = new CurrencyPair("BTC", "MXN");
		for (int i = 0; i < 100; i++) {
			OrderBook ob = service.getOrderBook(cp);
			System.out.println(ob);
			
		}
	}
```
Which will throw you a NPE. The real error that is being returned is `{"error":{"code":200,"message":"Too many requests"}}` but this doesn't get passed along, and so the orderbook is just `null`. 

I believe the exception should be thrown in this code in BitsoMarketDataServiceRaw:
```
  public BitsoOrderBook getBitsoOrderBook() throws IOException {
    BitsoOrderBook book = null;
    try {
      book = bitso.getOrderBook();
    } catch (BitsoException e) {
      logger.warn("Received a BitsoException:", e);
    }
    return book;
  }
```
The problem is the exception is never thrown, and so nothing is caught.  I even checked for instantiation in the BitsoException class, but it never is being instantiated.

**Comment by mmazi** [comment]
You're right, `BitsoException` never gets instantiated. (BTW, this also means catching it in getBitsoOrderBook() as you suggested wouldn't work.) This is because neither of the [two conditions](https://github.com/mmazi/rescu/wiki/Exception-handling#triggering-exception-parsing-based-on-json-content) that make rescu parse the response as the declared exception is satisfied: Bitso returns HTTP code 200, and the (error) response is parseable as an (empty) `BitsoOrderBook`.

[This](https://github.com/timmolter/XChange/pull/997) fixes it.

Thanks for providing the test code.

**Comment by bryan4887** [comment]
Excellent.  I tested it and it works.  I added some logic to retry the call if this "too many requests" error is encountered. Let me know what you think.  https://github.com/timmolter/XChange/pull/998
